export const productos = [
  {
    id: 1,
    nombre: "iPhone 14",
    precio: 950000,
    img: "./assets/img/Iphon14.jpg",
    categoria: "Celulares",
  },
  {
    id: 2,
    nombre: "Samsung Galaxy S23",
    precio: 870000,
    img: "./assets/img/galaxy-s23.jpg",
    categoria: "Celulares",
  },
  {
    id: 3,
    nombre: "Motorola Edge 40",
    precio: 520000,
    img: "./assets/img/moto-edge40.jpg",
    categoria: "Celulares",
  },
  {
    id: 4,
    nombre: "Xiaomi Redmi Note 13",
    precio: 380000,
    img: "./assets/img/redminote13.jpg",
    categoria: "Celulares",
  },
  {
    id: 5,
    nombre: "iPhone SE (3ra Gen)",
    precio: 450000,
    img: "./assets/img/iphon-13promax.jpg",
    categoria: "Celulares",
  },
  {
    id: 6,
    nombre: "PlayStation 5",
    precio: 890000,
    img: "./assets/img/ps5.jpg",
    categoria: "Consolas",
  },
  {
    id: 7,
    nombre: "Xbox Series X",
    precio: 870000,
    img: "./assets/img/xbox-seriesx.jpg",
    categoria: "Consolas",
  },
  {
    id: 8,
    nombre: "Nintendo Switch OLED",
    precio: 650000,
    img: "./assets/img/switch-oled.jpg",
    categoria: "Consolas",
  },
  {
    id: 9,
    nombre: "PlayStation 4 Slim",
    precio: 480000,
    img: "./assets/img/ps4-slim.jpg",
    categoria: "Consolas",
  },
  {
    id: 10,
    nombre: "Xbox Series S",
    precio: 520000,
    img: "./assets/img/xbox-seriess.jpg",
    categoria: "Consolas",
  },
];
